#' @keywords internal
update_resource <- function(path, dots) {

  url <- build_url(path, fields = "id")

  resp <-
    httr::PATCH(url, gc_token(), encode = "json",
                body = dots) %>%
    httr::stop_for_status()

  return(invisible(NULL))

}

#' Generalized GET method
#'
#' @param path Path of the HTTP request
#' @param fields Fields to be included in the response, as a character
#'   vector.
#' @param \dots Additional parameters to be passed to \code{build_url},
#'
#' @return If request was successful, the API response. Otherwise, an
#'   error or warning, as generated by \code{httr::stop_for_status}.
#'
#' @keywords internal
GET_resource <- function(path, fields = NULL) {

  url <- build_url(path, fields = fields)

  httr::GET(url, gc_token()) %>%
    httr::stop_for_status()

}
